# Generated by Django 3.1.7 on 2021-03-07 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Minivan', 'Jeep'), ('Jeep', 'Jeep'), ('Pickup', 'Pickup')], default='Sedan', max_length=100)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Electro', 'Electro'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=50)),
                ('mileage', models.IntegerField(default=0)),
                ('colour', models.CharField(choices=[('Ağ', 'Ağ'), ('Bej', 'Bej'), ('Bənövşəyi', 'Bənövşəyi'), ('Boz', 'Boz'), ('Çəhrayı', 'Çəhrayı'), ('Göy', 'Göy'), ('Gümüşü', 'Gümüşü'), ('Mavi', 'Mavi'), ('Narıncı', 'Narıncı'), ('Qara', 'Qara'), ('Qəhvəyi', 'Qəhvəyi'), ('Qırmızı', 'Qırmızı'), ('Qızılı', 'Qızılı'), ('Sarı', 'Sarı'), ('Tünd qırmızı', 'Tünd qırmızı'), ('Yaş Asfalt', 'Yaş Asfalt'), ('Yaşıl', 'Yaşıl')], default='Ağ', max_length=100)),
                ('car_release_date', models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('description', models.TextField(default='', max_length=5000)),
                ('car_image', models.ImageField(blank=True, upload_to='media/')),
                ('price', models.IntegerField(default=100, verbose_name='Qiymet')),
                ('owner_name', models.CharField(default=None, max_length=100)),
                ('owner_city', models.CharField(choices=[('Ağcabədi', 'Ağcabədi'), ('Ağdam', 'Ağdam'), ('Ağdaş', 'Ağdaş'), ('Ağdərə', 'Ağdərə'), ('Ağstafa', 'Ağstafa'), ('Ağsu', 'Ağsu'), ('Astara', 'Astara'), ('Babək', 'Babək'), ('Bakı', 'Bakı'), ('Balakən', 'Balakən'), ('Beyləqan', 'Beyləqan'), ('Bərdə', 'Bərdə'), ('Biləsuvar', 'Biləsuvar'), ('Cəbrayıl', 'Cəbrayıl'), ('Cəlilabad', 'Cəlilabad'), ('Culfa', 'Culfa'), ('Daşkəsən', 'Daşkəsən'), ('Dəliməmmədli', 'Dəliməmmədli'), ('Füzuli', 'Füzuli'), ('Gədəbəy', 'Gədəbəy'), ('Gəncə', 'Gəncə'), ('Goranboy', 'Goranboy'), ('Göyçay', 'Göyçay'), ('Göygöl', 'Göygöl'), ('Göytəpə', 'Göytəpə'), ('Hacıqabul', 'Hacıqabul'), ('Horadiz', 'Horadiz'), ('Xaçmaz', 'Xaçmaz'), ('Xankəndi', 'Xankəndi'), ('Xocalı', 'Xocalı'), ('Xocavənd', 'Xocavənd'), ('Xırdalan', 'Xırdalan'), ('Xızı', 'Xızı'), ('Xudat', 'Xudat'), ('İmişli', 'İmişli'), ('İsmayıllı', 'İsmayıllı'), ('Kəlbəcər', 'Kəlbəcər'), ('Kürdəmir', 'Kürdəmir'), ('Qax', 'Qax'), ('Qazax', 'Qazax'), ('Qəbələ', 'Qəbələ'), ('Qobustan', 'Qobustan'), ('Qovlar', 'Qovlar'), ('Quba', 'Quba'), ('Qubadlı', 'Qubadlı'), ('Qusar', 'Qusar'), ('Laçın', 'Laçın'), ('Lerik', 'Lerik'), ('Lənkəran', 'Lənkəran'), ('Liman', 'Liman'), ('Masallı', 'Masallı'), ('Mingəçevir', 'Mingəçevir'), ('Naftalan', 'Naftalan'), ('Naxçıvan', 'Naxçıvan'), ('Neftçala', 'Neftçala'), ('Oğuz', 'Oğuz'), ('Ordubad', 'Ordubad'), ('Saatlı', 'Saatlı'), ('Sabirabad', 'Sabirabad'), ('Salyan', 'Salyan'), ('Samux', 'Samux'), ('Siyəzən', 'Siyəzən'), ('Sumqayıt', 'Sumqayıt'), ('Şabran', 'Şabran'), ('Şahbuz', 'Şahbuz'), ('Şamaxı', 'Şamaxı'), ('Şəki', 'Şəki'), ('Şəmkir', 'Şəmkir'), ('Şərur', 'Şərur'), ('Şirvan', 'Şirvan'), ('Şuşa', 'Şuşa'), ('Tərtər', 'Tərtər'), ('Tovuz', 'Tovuz'), ('Ucar', 'Ucar'), ('Yardımlı', 'Yardımlı'), ('Yevlax', 'Yevlax'), ('Zaqatala', 'Zaqatala'), ('Zəngilan', 'Zəngilan'), ('Zərdab', 'Zərdab')], default='Bakı', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('moderate_on', models.BooleanField(default=False)),
                ('brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brandname')),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brandname')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='media/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.modelname'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
